Architecture: "local-rnn"

Seed: 42

Setting: "en22"

Logger:
    save_dir: "experiments/"

Checkpointer:
    save_top_k: 1
    save_last: True
    every_n_val_epochs: 1

Trainer:
    gpus: [6]
    strategy: 'ddp'
    #deterministic: True
    log_every_n_steps: 32
    accumulate_grad_batches: 8
    #profiler: 'advanced'
    #fast_dev_run: True
    #log_gpu_memory: 'all'
    #weights_summary: 'full'
    max_epochs: 150
    #limit_train_batches: 128
    #limit_val_batches: 64
    gradient_clip_val: 1
    val_check_interval: 1.0
  
Data:
    base_dir: "/workspace/data/UC1/L2_minicubes/"
    test_track: "iid"
    train_batch_size: 4 #96
    val_batch_size: 1
    test_batch_size: 1 #96
    num_workers: 8 #2

Task:
    loss:
        name: "masked"
        args: {
            distance_type: "L2",
            rescale: False
        }
        dist_scale: 1
        state_shedule: {
            initial_weight: 0,
            increase_from_step: 1500,
            weight_step: 0.00001,
            max_weight: 1
        }
        inference_shedule: {
            initial_weight: 0,
            increase_from_step: 3000,
            weight_step: 0.0000000001,
            max_weight: 1
        }
        residuals_shedule: {
            initial_weight: 0,
            increase_from_step: 1500,
            weight_step: 0.00001,
            max_weight: 1
        }
        ndvi: True
        min_lc: 2
        max_lc: 6
        comp_ndvi: False

    context_length: 35
    target_length: 10
    n_stochastic_preds: 1
    optimization:
        optimizer:
            - 
                name: Adam
                args: 
                    betas: [0.9, 0.999]
                lr_per_sample: 0.0000005
        lr_shedule:
            -
                name: MultiStepLR
                args:
                    milestones: [600] #[2, 20, 50, 90]
                    gamma: 0.1
    n_log_batches: 8
    train_batch_size: 4 #96
    val_batch_size: 1
    test_batch_size: 1 #96
    compute_metric_on_test: True

Model:
    state_encoder_name: FPN
    state_encoder_args: 
        encoder_name: timm-efficientnet-b3
        encoder_weights: noisy-student
        in_channels: 46
        classes: 192
        decoder_merge_policy: cat
        decoder_dropout: 0
    update_encoder_name: efficientnet_b1
    update_encoder_nclasses: 96
    update_encoder_inchannels: 24
    train_lstm_npixels: 4096
